app:
    resource: '@AppBundle/Controller/AppController.php'
    type: annotation
    prefix: app

service:
    resource: '@AppBundle/Controller/ServiceController.php'
    type: annotation
    prefix: service

login:
    resource: '@AppBundle/Controller/LoginController.php'
    type: annotation

admin:
    resource: '@AppBundle/Controller/AdminController.php'
    type: annotation
    prefix: admin

espaceperso:
    resource: '@AppBundle/Controller/EspacePersoController.php'
    type: annotation
    prefix: espace-perso

fos_test:
    resource: '@AppBundle/Controller/FosController.php'
    type: annotation
    prefix: /fosuser

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /fosuser

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /fosuser/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /fosuser/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /fosuser/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /fosuser/profile