AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        nom:
            type: string
            length: '255'
        description:
            type: text
        prix:
            type: float
        prix2:
            type: decimal
            precision: '10'
            scale: '2'
            nullable: true
        stock:
            type: smallint
        slug:
            type: string
            length: '255'

    manyToMany:
        commandes:
            targetEntity: Commande
            inversedBy: articles

    lifecycleCallbacks:
        prePersist: [ prePersist ]
        # sur l'evenement prePersist d'un objet Article
        # la fonction prePersist de l'entité Article sera appelée
