AppBundle\Entity\Utilisateur:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        email:
            type: string
            length: '255'
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        codePostal:
            type: string
            length: '5'
        telephone:
            type: string
            length: '10'
        username:
            type: string
            length: '50'
            unique: true
        password:
            type: string
            length: '255'

    oneToMany:
        commandes:
            targetEntity: Commande
            mappedBy: utilisateur

    lifecycleCallbacks: {  }
